# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Constantine/OneDrive - Technion/Studies/FireSourceDetection/repo/NetFPGA-live-fork/lib/hw/contrib/cores/spad_controller/spad_controller.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Constantine/OneDrive - Technion/Studies/FireSourceDetection/repo/NetFPGA-live-fork/lib/hw/contrib/cores/spad_controller/spad_controller.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{C:/Users/Constantine/OneDrive - Technion/Studies/FireSourceDetection/repo/NetFPGA-live-fork/lib/hw/contrib/cores/spad_controller/spad_controller.srcs/sources_1/new/controller.v}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top controller -part xc7k70tfbv676-1


write_checkpoint -force -noxdef controller.dcp

catch { report_utilization -file controller_utilization_synth.rpt -pb controller_utilization_synth.pb }
